<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Auditlog extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Auditlog_model');
    } 

    /*
     * Listing of auditlogs
     */
    function index()
    {
        $this->load->library('loginvalidation');
        $this->loginvalidation->isValid();
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('auditlog/index?');
        $config['total_rows'] = $this->Auditlog_model->get_all_auditlogs_count();
        $this->pagination->initialize($config);

        $data['auditlogs'] = $this->Auditlog_model->get_all_auditlogs($params);
        
        $data['_view'] = 'auditlog/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new auditlog
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('logType','LogType','max_length[80]');
		$this->form_validation->set_rules('description','Description','max_length[500]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'userID' => $this->input->post('userID'),
				'logType' => $this->input->post('logType'),
				'timeStamp' => $this->input->post('timeStamp'),
				'description' => $this->input->post('description'),
            );
            
            $auditlog_id = $this->Auditlog_model->add_auditlog($params);
            redirect('auditlog/index');
        }
        else
        {
			$this->load->model('User_model');
			$data['all_users'] = $this->User_model->get_all_users();
            
            $data['_view'] = 'auditlog/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a auditlog
     */
    function edit($auditID)
    {   
        // check if the auditlog exists before trying to edit it
        $data['auditlog'] = $this->Auditlog_model->get_auditlog($auditID);
        
        if(isset($data['auditlog']['auditID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('logType','LogType','max_length[80]');
			$this->form_validation->set_rules('description','Description','max_length[500]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'userID' => $this->input->post('userID'),
					'logType' => $this->input->post('logType'),
					'timeStamp' => date('Y-m-d H:i:s'),
					'description' => $this->input->post('description'),
                );

                $this->Auditlog_model->update_auditlog($auditID,$params);            
                redirect('auditlog/index');
            }
            else
            {
				$this->load->model('User_model');
				$data['all_users'] = $this->User_model->get_all_users();

                $data['_view'] = 'auditlog/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The auditlog you are trying to edit does not exist.');
    } 

    /*
     * Deleting auditlog
     */
    function remove($auditID)
    {
        $auditlog = $this->Auditlog_model->get_auditlog($auditID);

        // check if the auditlog exists before trying to delete it
        if(isset($auditlog['auditID']))
        {
            $this->Auditlog_model->delete_auditlog($auditID);
            redirect('auditlog/index');
        }
        else
            show_error('The auditlog you are trying to delete does not exist.');
    }
    
}
