<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Degreeprogram extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Degreeprogram_model');
    } 

    /*
     * Listing of degreeprograms
     */
    function index()
    {
        $this->load->library('loginvalidation');
        $this->loginvalidation->isValid();
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('degreeprogram/index?');
        $config['total_rows'] = $this->Degreeprogram_model->get_all_degreeprograms_count();
        $this->pagination->initialize($config);

        $data['degreeprograms'] = $this->Degreeprogram_model->get_all_degreeprograms($params);
        
        $data['_view'] = 'degreeprogram/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new degreeprogram
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','max_length[60]');
		$this->form_validation->set_rules('programCode','ProgramCode','max_length[10]');
		$this->form_validation->set_rules('description','Description','max_length[500]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'programCode' => $this->input->post('programCode'),
				'description' => $this->input->post('description'),
            );
            
            $degreeprogram_id = $this->Degreeprogram_model->add_degreeprogram($params);
            redirect('degreeprogram/index');
        }
        else
        {            
            $data['_view'] = 'degreeprogram/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a degreeprogram
     */
    function edit($programID)
    {   
        // check if the degreeprogram exists before trying to edit it
        $data['degreeprogram'] = $this->Degreeprogram_model->get_degreeprogram($programID);
        
        if(isset($data['degreeprogram']['programID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','max_length[60]');
			$this->form_validation->set_rules('programCode','ProgramCode','max_length[10]');
			$this->form_validation->set_rules('description','Description','max_length[500]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'programCode' => $this->input->post('programCode'),
					'description' => $this->input->post('description'),
                );

                $this->Degreeprogram_model->update_degreeprogram($programID,$params);            
                redirect('degreeprogram/index');
            }
            else
            {
                $data['_view'] = 'degreeprogram/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The degreeprogram you are trying to edit does not exist.');
    } 

    /*
     * Deleting degreeprogram
     */
    function remove($programID)
    {
        $degreeprogram = $this->Degreeprogram_model->get_degreeprogram($programID);

        // check if the degreeprogram exists before trying to delete it
        if(isset($degreeprogram['programID']))
        {
            $this->Degreeprogram_model->delete_degreeprogram($programID);
            redirect('degreeprogram/index');
        }
        else
            show_error('The degreeprogram you are trying to delete does not exist.');
    }
    
}
