<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Programcourse extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Programcourse_model');
    } 

    /*
     * Listing of programcourses
     */
    function index()
    {
        $this->load->library('loginvalidation');
        $this->loginvalidation->isValid();
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('programcourse/index?');
        $config['total_rows'] = $this->Programcourse_model->get_all_programcourses_count();
        $this->pagination->initialize($config);

        $data['programcourses'] = $this->Programcourse_model->get_all_programcourses($params);
        
        $data['_view'] = 'programcourse/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new programcourse
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'programID' => $this->input->post('programID'),
				'courseID' => $this->input->post('courseID'),
            );
            
            $programcourse_id = $this->Programcourse_model->add_programcourse($params);
            redirect('programcourse/index');
        }
        else
        {			$data['all_programcourses'] = $this->Programcourse_model->get_all_programcourses();

			$this->load->model('Course_model');
			$data['all_courses'] = $this->Course_model->get_all_courses();
            
            $data['_view'] = 'programcourse/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a programcourse
     */
    function edit($refNo)
    {   
        // check if the programcourse exists before trying to edit it
        $data['programcourse'] = $this->Programcourse_model->get_programcourse($refNo);
        
        if(isset($data['programcourse']['refNo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'programID' => $this->input->post('programID'),
					'courseID' => $this->input->post('courseID'),
                );

                $this->Programcourse_model->update_programcourse($refNo,$params);            
                redirect('programcourse/index');
            }
            else
            {				$data['all_programcourses'] = $this->Programcourse_model->get_all_programcourses();

				$this->load->model('Course_model');
				$data['all_courses'] = $this->Course_model->get_all_courses();

                $data['_view'] = 'programcourse/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The programcourse you are trying to edit does not exist.');
    } 

    /*
     * Deleting programcourse
     */
    function remove($refNo)
    {
        $programcourse = $this->Programcourse_model->get_programcourse($refNo);

        // check if the programcourse exists before trying to delete it
        if(isset($programcourse['refNo']))
        {
            $this->Programcourse_model->delete_programcourse($refNo);
            redirect('programcourse/index');
        }
        else
            show_error('The programcourse you are trying to delete does not exist.');
    }
    
}
