<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Schedule extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Schedule_model');
    } 

    /*
     * Listing of schedule
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('schedule/index?');
        $config['total_rows'] = $this->Schedule_model->get_all_schedule_count();
        $this->pagination->initialize($config);

        $data['schedule'] = $this->Schedule_model->get_all_schedule($params);
        
        $data['_view'] = 'schedule/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new schedule
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('day','Day','max_length[9]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'day' => $this->input->post('day'),
				'timeStart' => $this->input->post('timeStart'),
				'timeEnd' => $this->input->post('timeEnd'),
            );
            
            $schedule_id = $this->Schedule_model->add_schedule($params);
            redirect('schedule/index');
        }
        else
        {            
            $data['_view'] = 'schedule/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a schedule
     */
    function edit($scheduleID)
    {   
        // check if the schedule exists before trying to edit it
        $data['schedule'] = $this->Schedule_model->get_schedule($scheduleID);
        
        if(isset($data['schedule']['scheduleID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('day','Day','max_length[9]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'day' => $this->input->post('day'),
					'timeStart' => $this->input->post('timeStart'),
					'timeEnd' => $this->input->post('timeEnd'),
                );

                $this->Schedule_model->update_schedule($scheduleID,$params);            
                redirect('schedule/index');
            }
            else
            {
                $data['_view'] = 'schedule/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The schedule you are trying to edit does not exist.');
    } 

    /*
     * Deleting schedule
     */
    function remove($scheduleID)
    {
        $schedule = $this->Schedule_model->get_schedule($scheduleID);

        // check if the schedule exists before trying to delete it
        if(isset($schedule['scheduleID']))
        {
            $this->Schedule_model->delete_schedule($scheduleID);
            redirect('schedule/index');
        }
        else
            show_error('The schedule you are trying to delete does not exist.');
    }
    
}
