<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Student extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Student_model');
    } 

    /*
     * Listing of students
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('student/index?');
        $config['total_rows'] = $this->Student_model->get_all_students_count();
        $this->pagination->initialize($config);

        $data['students'] = $this->Student_model->get_all_students($params);
        
        $data['_view'] = 'student/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new student
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('studentNo','StudentNo','max_length[8]');
		$this->form_validation->set_rules('status','Status','max_length[10]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'userID' => $this->input->post('userID'),
				'programID' => $this->input->post('programID'),
				'studentNo' => $this->input->post('studentNo'),
				'status' => $this->input->post('status'),
				'dateAdded' => $this->input->post('dateAdded'),
				'dateModified' => $this->input->post('dateModified'),
            );
            
            $student_id = $this->Student_model->add_student($params);
            redirect('student/index');
        }
        else
        {
			$this->load->model('User_model');
			$data['all_users'] = $this->User_model->get_all_users();

			$this->load->model('Programcourse_model');
			$data['all_programcourses'] = $this->Programcourse_model->get_all_programcourses();
            
            $data['_view'] = 'student/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a student
     */
    function edit($studentID)
    {   
        // check if the student exists before trying to edit it
        $data['student'] = $this->Student_model->get_student($studentID);
        
        if(isset($data['student']['studentID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('studentNo','StudentNo','max_length[8]');
			$this->form_validation->set_rules('status','Status','max_length[10]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'userID' => $this->input->post('userID'),
					'programID' => $this->input->post('programID'),
					'studentNo' => $this->input->post('studentNo'),
					'status' => $this->input->post('status'),
					'dateAdded' => $this->input->post('dateAdded'),
					'dateModified' => $this->input->post('dateModified'),
                );

                $this->Student_model->update_student($studentID,$params);            
                redirect('student/index');
            }
            else
            {
				$this->load->model('User_model');
				$data['all_users'] = $this->User_model->get_all_users();

				$this->load->model('Programcourse_model');
				$data['all_programcourses'] = $this->Programcourse_model->get_all_programcourses();

                $data['_view'] = 'student/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The student you are trying to edit does not exist.');
    } 

    /*
     * Deleting student
     */
    function remove($studentID)
    {
        $student = $this->Student_model->get_student($studentID);

        // check if the student exists before trying to delete it
        if(isset($student['studentID']))
        {
            $this->Student_model->delete_student($studentID);
            redirect('student/index');
        }
        else
            show_error('The student you are trying to delete does not exist.');
    }
    
}
