<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tutor extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tutor_model');
    } 

    /*
     * Listing of tutors
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tutor/index?');
        $config['total_rows'] = $this->Tutor_model->get_all_tutors_count();
        $this->pagination->initialize($config);

        $data['tutors'] = $this->Tutor_model->get_all_tutors($params);
        
        $data['_view'] = 'tutor/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tutor
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('tutorType','TutorType','max_length[80]');
		$this->form_validation->set_rules('status','Status','max_length[10]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'userID' => $this->input->post('userID'),
				'tutorType' => $this->input->post('tutorType'),
				'dateAdded' => $this->input->post('dateAdded'),
				'dateModified' => $this->input->post('dateModified'),
				'status' => $this->input->post('status'),
            );
            
            $tutor_id = $this->Tutor_model->add_tutor($params);
            redirect('tutor/index');
        }
        else
        {
			$this->load->model('User_model');
			$data['all_users'] = $this->User_model->get_all_users();
            
            $data['_view'] = 'tutor/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tutor
     */
    function edit($tutorID)
    {   
        // check if the tutor exists before trying to edit it
        $data['tutor'] = $this->Tutor_model->get_tutor($tutorID);
        
        if(isset($data['tutor']['tutorID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('tutorType','TutorType','max_length[80]');
			$this->form_validation->set_rules('status','Status','max_length[10]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'userID' => $this->input->post('userID'),
					'tutorType' => $this->input->post('tutorType'),
					'dateAdded' => $this->input->post('dateAdded'),
					'dateModified' => $this->input->post('dateModified'),
					'status' => $this->input->post('status'),
                );

                $this->Tutor_model->update_tutor($tutorID,$params);            
                redirect('tutor/index');
            }
            else
            {
				$this->load->model('User_model');
				$data['all_users'] = $this->User_model->get_all_users();

                $data['_view'] = 'tutor/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tutor you are trying to edit does not exist.');
    } 

    /*
     * Deleting tutor
     */
    function remove($tutorID)
    {
        $tutor = $this->Tutor_model->get_tutor($tutorID);

        // check if the tutor exists before trying to delete it
        if(isset($tutor['tutorID']))
        {
            $this->Tutor_model->delete_tutor($tutorID);
            redirect('tutor/index');
        }
        else
            show_error('The tutor you are trying to delete does not exist.');
    }
    
}
