<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tutorexpertise extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tutorexpertise_model');
    } 

    /*
     * Listing of tutorexpertise
     */
    function index()
    {
        $this->load->library('loginvalidation');
        $this->loginvalidation->isValid();
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tutorexpertise/index?');
        $config['total_rows'] = $this->Tutorexpertise_model->get_all_tutorexpertise_count();
        $this->pagination->initialize($config);

        $data['tutorexpertise'] = $this->Tutorexpertise_model->get_all_tutorexpertise($params);
        
        $data['_view'] = 'tutorexpertise/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tutorexpertise
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tutorID' => $this->input->post('tutorID'),
				'courseID' => $this->input->post('courseID'),
            );
            
            $tutorexpertise_id = $this->Tutorexpertise_model->add_tutorexpertise($params);
            redirect('tutorexpertise/index');
        }
        else
        {
			$this->load->model('Tutor_model');
			$data['all_tutors'] = $this->Tutor_model->get_all_tutors();

			$this->load->model('Course_model');
			$data['all_courses'] = $this->Course_model->get_all_courses();
            
            $data['_view'] = 'tutorexpertise/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tutorexpertise
     */
    function edit($expertiseID)
    {   
        // check if the tutorexpertise exists before trying to edit it
        $data['tutorexpertise'] = $this->Tutorexpertise_model->get_tutorexpertise($expertiseID);
        
        if(isset($data['tutorexpertise']['expertiseID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tutorID' => $this->input->post('tutorID'),
					'courseID' => $this->input->post('courseID'),
                );

                $this->Tutorexpertise_model->update_tutorexpertise($expertiseID,$params);            
                redirect('tutorexpertise/index');
            }
            else
            {
				$this->load->model('Tutor_model');
				$data['all_tutors'] = $this->Tutor_model->get_all_tutors();

				$this->load->model('Course_model');
				$data['all_courses'] = $this->Course_model->get_all_courses();

                $data['_view'] = 'tutorexpertise/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tutorexpertise you are trying to edit does not exist.');
    } 

    /*
     * Deleting tutorexpertise
     */
    function remove($expertiseID)
    {
        $tutorexpertise = $this->Tutorexpertise_model->get_tutorexpertise($expertiseID);

        // check if the tutorexpertise exists before trying to delete it
        if(isset($tutorexpertise['expertiseID']))
        {
            $this->Tutorexpertise_model->delete_tutorexpertise($expertiseID);
            redirect('tutorexpertise/index');
        }
        else
            show_error('The tutorexpertise you are trying to delete does not exist.');
    }
    
}
