<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usertype extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Usertype_model');
    } 

    /*
     * Listing of usertypes
     */
    function index()
    {
        $this->load->library('loginvalidation');
        $this->loginvalidation->isValid();
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('usertype/index?');
        $config['total_rows'] = $this->Usertype_model->get_all_usertypes_count();
        $this->pagination->initialize($config);

        $data['usertypes'] = $this->Usertype_model->get_all_usertypes($params);
        
        $data['_view'] = 'usertype/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new usertype
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('userType','UserType','max_length[25]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'userType' => $this->input->post('userType'),
            );
            
            $usertype_id = $this->Usertype_model->add_usertype($params);
            redirect('usertype/index');
        }
        else
        {            
            $data['_view'] = 'usertype/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a usertype
     */
    function edit($typeID)
    {   
        // check if the usertype exists before trying to edit it
        $data['usertype'] = $this->Usertype_model->get_usertype($typeID);
        
        if(isset($data['usertype']['typeID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('userType','UserType','max_length[25]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'userType' => $this->input->post('userType'),
                );

                $this->Usertype_model->update_usertype($typeID,$params);            
                redirect('usertype/index');
            }
            else
            {
                $data['_view'] = 'usertype/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The usertype you are trying to edit does not exist.');
    } 

    /*
     * Deleting usertype
     */
    function remove($typeID)
    {
        $usertype = $this->Usertype_model->get_usertype($typeID);

        // check if the usertype exists before trying to delete it
        if(isset($usertype['typeID']))
        {
            $this->Usertype_model->delete_usertype($typeID);
            redirect('usertype/index');
        }
        else
            show_error('The usertype you are trying to delete does not exist.');
    }
    
}
