<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    } 

    /*
     * Listing of users
     */
    function index()
    {
        $this->load->library('loginvalidation');
        $this->loginvalidation->isValid();
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('user/index?');
        $config['total_rows'] = $this->User_model->get_all_users_count();
        $this->pagination->initialize($config);

        $data['users'] = $this->User_model->get_all_users($params);
        
        $data['_view'] = 'user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user
     */
    function add()
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('username','Username','max_length[50]');
        $this->form_validation->set_rules('password','Password','max_length[300]');        
        $this->form_validation->set_rules('firstName','FirstName','max_length[80]');
		$this->form_validation->set_rules('lastName','LastName','max_length[50]');
		$this->form_validation->set_rules('middleName','MiddleName','max_length[50]');
		$this->form_validation->set_rules('emailAddress','EmailAddress','max_length[100]|valid_email');
		$this->form_validation->set_rules('contactNo','ContactNo','max_length[15]');
		
		if($this->form_validation->run())     
        {   
            $hashed = 
            $params = array(
                'typeID' => $this->input->post('typeID'),
                'username' => $this->input->post('username'),
                'password' => password_hash($this->input->post('password'), PASSWORD_BCRYPT),
				'firstName' => $this->input->post('firstName'),
				'lastName' => $this->input->post('lastName'),
				'middleName' => $this->input->post('middleName'),
				'emailAddress' => $this->input->post('emailAddress'),
				'contactNo' => $this->input->post('contactNo'),
            );
            
            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        }
        else
        {
			$this->load->model('Usertype_model');
			$data['all_usertypes'] = $this->Usertype_model->get_all_usertypes();
            
            $data['_view'] = 'user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user
     */
    function edit($userID)
    {   
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($userID);
        
        if(isset($data['user']['userID']))
        {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('username','Username','max_length[50]');
            $this->form_validation->set_rules('password','Password','max_length[300]'); 
			$this->form_validation->set_rules('firstName','FirstName','max_length[80]');
			$this->form_validation->set_rules('lastName','LastName','max_length[50]');
			$this->form_validation->set_rules('middleName','MiddleName','max_length[50]');
			$this->form_validation->set_rules('emailAddress','EmailAddress','max_length[100]|valid_email');
			$this->form_validation->set_rules('contactNo','ContactNo','max_length[15]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
                    'typeID' => $this->input->post('typeID'),
                    'username' => $this->input->post('username'),
                    'password' => password_hash($this->input->post('password'), PASSWORD_BCRYPT),
					'firstName' => $this->input->post('firstName'),
					'lastName' => $this->input->post('lastName'),
					'middleName' => $this->input->post('middleName'),
					'emailAddress' => $this->input->post('emailAddress'),
					'contactNo' => $this->input->post('contactNo'),
                );

                $this->User_model->update_user($userID,$params);            
                redirect('user/index');
            }
            else
            {
				$this->load->model('Usertype_model');
				$data['all_usertypes'] = $this->Usertype_model->get_all_usertypes();

                $data['_view'] = 'user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
    } 

    /*
     * Deleting user
     */
    function remove($userID)
    {
        $user = $this->User_model->get_user($userID);

        // check if the user exists before trying to delete it
        if(isset($user['userID']))
        {
            $this->User_model->delete_user($userID);
            redirect('user/index');
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }
    
}
