<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Auditlog_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get auditlog by auditID
     */
    function get_auditlog($auditID)
    {
        return $this->db->get_where('auditlogs',array('auditID'=>$auditID))->row_array();
    }
    
    /*
     * Get all auditlogs count
     */
    function get_all_auditlogs_count()
    {
        $this->db->from('auditlogs');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all auditlogs
     */
    function get_all_auditlogs($params = array())
    {
        $this->db->select('auditID, users.userID, users.lastName, users.firstName, logType, description, timeStamp');    
        $this->db->from('auditlogs');
        $this->db->join('users', 'auditlogs.userID = users.userID');

        $this->db->order_by('auditID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get()->result_array();


    }
        
    /*
     * function to add new auditlog
     */
    function add_auditlog($params)
    {
        $this->db->insert('auditlogs',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update auditlog
     */
    function update_auditlog($auditID,$params)
    {
        $this->db->where('auditID',$auditID);
        return $this->db->update('auditlogs',$params);
    }
    
    /*
     * function to delete auditlog
     */
    function delete_auditlog($auditID)
    {
        return $this->db->delete('auditlogs',array('auditID'=>$auditID));
    }
}
