<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Degreeprogram_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get degreeprogram by programID
     */
    function get_degreeprogram($programID)
    {
        return $this->db->get_where('degreeprograms',array('programID'=>$programID))->row_array();
    }
    
    /*
     * Get all degreeprograms count
     */
    function get_all_degreeprograms_count()
    {
        $this->db->from('degreeprograms');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all degreeprograms
     */
    function get_all_degreeprograms($params = array())
    {
        $this->db->order_by('programID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('degreeprograms')->result_array();
    }
        
    /*
     * function to add new degreeprogram
     */
    function add_degreeprogram($params)
    {
        $this->db->insert('degreeprograms',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update degreeprogram
     */
    function update_degreeprogram($programID,$params)
    {
        $this->db->where('programID',$programID);
        return $this->db->update('degreeprograms',$params);
    }
    
    /*
     * function to delete degreeprogram
     */
    function delete_degreeprogram($programID)
    {
        return $this->db->delete('degreeprograms',array('programID'=>$programID));
    }
}
