<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Schedule_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get schedule by scheduleID
     */
    function get_schedule($scheduleID)
    {
        return $this->db->get_where('schedule',array('scheduleID'=>$scheduleID))->row_array();
    }
    
    /*
     * Get all schedule count
     */
    function get_all_schedule_count()
    {
        $this->db->from('schedule');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all schedule
     */
    function get_all_schedule($params = array())
    {
        $this->db->order_by('scheduleID', 'asc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('schedule')->result_array();
    }
        
    /*
     * function to add new schedule
     */
    function add_schedule($params)
    {
        $this->db->insert('schedule',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update schedule
     */
    function update_schedule($scheduleID,$params)
    {
        $this->db->where('scheduleID',$scheduleID);
        return $this->db->update('schedule',$params);
    }
    
    /*
     * function to delete schedule
     */
    function delete_schedule($scheduleID)
    {
        return $this->db->delete('schedule',array('scheduleID'=>$scheduleID));
    }
}
