<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usertype_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usertype by typeID
     */
    function get_usertype($typeID)
    {
        return $this->db->get_where('usertypes',array('typeID'=>$typeID))->row_array();
    }
    
    /*
     * Get all usertypes count
     */
    function get_all_usertypes_count()
    {
        $this->db->from('usertypes');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all usertypes
     */
    function get_all_usertypes($params = array())
    {
        $this->db->order_by('typeID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('usertypes')->result_array();
    }
        
    /*
     * function to add new usertype
     */
    function add_usertype($params)
    {
        $this->db->insert('usertypes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usertype
     */
    function update_usertype($typeID,$params)
    {
        $this->db->where('typeID',$typeID);
        return $this->db->update('usertypes',$params);
    }
    
    /*
     * function to delete usertype
     */
    function delete_usertype($typeID)
    {
        return $this->db->delete('usertypes',array('typeID'=>$typeID));
    }
}
